server:
  port: 8071
spring:
  application:
    name: consumer-service

#配置注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/

#日志分级
logging:
  level:
    com.yhc.consumer.controller: debug

#ribbon负载均衡超时配置
ribbon:
  ConnectionTimeOut: 1000   #默认为1秒，当1秒还没建立连接，则抛出异常。
  ReadTimeOut: 1000          #默认为1秒，当1秒还没读取到数据，则抛出异常。

#feign的hystrix配置
feign:
  hystrix:
    enabled: true    #开启hystrix


#hystrix配置(调用失败的时间)
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000

