#服务器的端口号
server:
  port: 10000
#设置在注册中心的服务名称
spring:
  application:
    name: eureka-service
#设置另一台eureka服务的地址(当前注册自己)
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
  #设置注册服务以ip显示
  #instance:
    #prefer-ip-address: true
    #注册的ip显示以下ip
    #ip-address: 127.0.0.1
